#!/bin/bash

# Script to verify Railway deployment và config

echo "======================================"
echo "🔍 RAILWAY DEPLOYMENT CHECKER"
echo "======================================"
echo ""

echo "📝 Recent commits:"
git log --oneline -3
echo ""

echo "======================================"
echo "⚠️  IMPORTANT: Vấn đề hiện tại"
echo "======================================"
echo ""
echo "Lỗi cho thấy Railway đang chạy CODE CŨ với Flask-Mail SMTP"
echo "Code mới đã được commit nhưng Railway chưa deploy hoặc thiếu config"
echo ""

echo "======================================"
echo "✅ GIẢI PHÁP - Làm theo thứ tự:"
echo "======================================"
echo ""

echo "1️⃣  VERIFY RAILWAY ĐÃ DEPLOY CODE MỚI CHƯA:"
echo "   - Vào: https://railway.app"
echo "   - Chọn project → service"
echo "   - Tab 'Deployments' → Xem deployment mới nhất"
echo "   - Check commit hash có phải '12fdab3' không?"
echo "   - Nếu KHÔNG → Click 'Deploy' hoặc 'Redeploy'"
echo ""

echo "2️⃣  SET BREVO_API_KEY TRÊN RAILWAY:"
echo "   - Tab 'Variables' → Click 'New Variable'"
echo "   - Name: BREVO_API_KEY"
echo "   - Value: xkeysib-GqFjavnHgtPCBIXU"
echo "   - Click 'Add' → Railway sẽ tự restart"
echo ""

echo "3️⃣  SET MAIL_DEFAULT_SENDER:"
echo "   - Name: MAIL_DEFAULT_SENDER"
echo "   - Value: (email đã verify trên Brevo)"
echo "   - Verify email tại: https://app.brevo.com/settings/senders"
echo ""

echo "4️⃣  XÓA HOẶC COMMENT CÁC BIẾN SMTP CŨ (nếu có):"
echo "   - MAIL_SERVER"
echo "   - MAIL_PORT"
echo "   - MAIL_USERNAME"
echo "   - MAIL_PASSWORD"
echo "   → Để code dùng Brevo API thay vì SMTP"
echo ""

echo "5️⃣  FORCE REDEPLOY (nếu cần):"
echo "   railway up --detach"
echo "   # Hoặc trên Dashboard: Deployments → ... → Redeploy"
echo ""

echo "6️⃣  XEM LOGS:"
echo "   railway logs"
echo "   # Tìm:"
echo "   #   - '📧 [BREVO API]' → Đang dùng API"
echo "   #   - '✅ [BREVO API] Email sent' → Thành công"
echo ""

echo "======================================"
echo "🐛 DEBUG: Nếu vẫn lỗi sau khi làm xong"
echo "======================================"
echo ""
echo "Check logs Railway có dòng này không:"
echo ""
echo "✅ ĐÚNG (dùng Brevo API):"
echo "   📧 [EMAIL SENDER] Using Brevo API (primary method)"
echo "   📧 [BREVO API] Starting email send to: ..."
echo ""
echo "❌ SAI (vẫn dùng SMTP):"
echo "   📧 [SMTP FALLBACK] Attempting to send email"
echo "   ❌ [EMAIL ERROR] TimeoutError"
echo ""
echo "Nếu vẫn thấy SMTP FALLBACK nghĩa là:"
echo "   → BREVO_API_KEY chưa được set"
echo "   → Hoặc Railway chưa restart sau khi set"
echo ""

echo "======================================"
echo "📞 Quick Commands"
echo "======================================"
echo ""
echo "# Check Railway env vars"
echo "railway variables"
echo ""
echo "# View logs real-time"
echo "railway logs"
echo ""
echo "# Redeploy"
echo "railway up --detach"
echo ""
